name: ccp-env
channels:
  - conda-forge
dependencies:
  - matplotlib==3.10.0
  - flask==3.1.0
  - joblib==1.4.2
  - numpy==2.2.1
  - pandas==2.2.3
  - scikit-learn==1.6.0
  - seaborn==0.13.2
  - snowflake-connector-python==3.12.4